[package]
name = "homomorph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mimalloc = "0.1.39"
rand = "0.8.5"
rayon = "1.10.0"

[profile.release]
codegen-units = 1
lto = "thin"

[build]
rustflags = ["-C", "target-cpu=native"]
