[package]
name = "homomorph"
version = "1.0.0"
edition = "2021"
description = "A Rust implementation of an homomorphic encryption scheme"
license = "MIT"
repository = "https://github.com/mathisbot/homomorph-rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = { version = "0.2.15", default-features = false, features = ["rdrand"] }
zeroize = { version = "1.8.1", default-features = false, features = ["alloc","zeroize_derive"] }

[dev-dependencies]
rand = "0.8.5"

[features]
default = []
custom_rand = ["getrandom/custom"]

[profile.release]
codegen-units = 1
lto = "thin"
