[package]
name = "homomorph"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[dev-dependencies]
mimalloc = "0.1.43"

[profile.release]
codegen-units = 1
lto = "thin"
