name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        profile: minimal
        components: rustfmt, clippy
        override: true

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Run extensive tests
      run: cargo test --release --verbose -- --ignored

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Check formatting
      run: cargo fmt -- --check

    # - name: Install tarpaulin
    #   run: cargo install cargo-tarpaulin

    # - name: Generate code coverage
    #   run: |
    #     cargo tarpaulin --out Xml
    #     bash <(curl -s https://codecov.io/bash) -f lcov.info

    # - name: Security audit
    #   run: cargo install cargo-audit
    # - name: Run security audit
    #   run: cargo audit
