name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        profile: minimal
        components: rustfmt, clippy
        override: true

    - name: Build
      run: cargo build --lib --verbose

    - name: Run basic tests
      run: cargo test --verbose

    - name: Run extensive tests
      run: cargo test --release --verbose -- --ignored

    - name: Run a basic example
      run: cargo run --release --example new_struct

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features --no-deps -- -D warnings

    - name: Check formatting
      run: cargo fmt -- --check

  x86_64-unknown-none:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-none
        profile: minimal
        override: true

    - name: Build
      run: cargo build --lib --verbose